//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wpfCrudEntities2 : DbContext
    {
        public wpfCrudEntities2()
            : base("name=wpfCrudEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BooksReservation> BooksReservations { get; set; }
        public virtual DbSet<LendingBook> LendingBooks { get; set; }
        public virtual DbSet<Reader> Readers { get; set; }
    }
}
